language: c

before_install:
  - sudo apt-get update
  - sudo apt-get install -q postgresql-server-dev-9.3 libcunit1-dev valgrind

addons:
  postgresql: "9.3" # for "installcheck"

before_script: ./autogen.sh

script:
  - ./configure CFLAGS="-Wall -O2 -g"
  - make
  - make check
  - valgrind --leak-check=full --error-exitcode=1 --show-leak-kinds=all lib/cunit/cu_tester
  - sudo make install
  - make installcheck || { cat pgsql/regression.diffs && false; }
